; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino

lib_deps = 
	feilipu/FreeRTOS
	duinowitchery/hd44780 

upload_protocol = custom
; upload_command = /usr/bin/picsimlab_tool loadhex "$BUILD_DIR/firmware.hex"
upload_command = C:\Users\henri\Downloads\picsimlab_win64\picsimlab_tool.exe loadhex "$BUILD_DIR/firmware.hex"
build_type = debug
debug_tool = custom
debug_port = localhost:1234
debug_build_flags = -O2 -g
debug_init_break = tbreak setup
debug_init_cmds =
    define pio_reset_halt_target
    end
    define pio_reset_run_target
    end
    target extended-remote $DEBUG_PORT
    $LOAD_CMDS
    pio_reset_halt_target
    $INIT_BREAK
